#
# |===============|
# |    Welcome    |
# |===============|
#
# Welcome in the HexChat config.yml!
# This config will try to explain as much as possible, so make sure you read the comments here.
#
# |===============|
# |    Support    |
# |===============|
#
# The best (and fastest) way to receive support is by joining my Discord Server (https://discord.gg/6dazXp6) and
# go to the #hexchat Text Channel.
# Alternatively can you ask for help on the Thread on Spigot: https://www.spigotmc.org/threads/447658
#
# Bug reports and feature requests are handled through GitHub: https://github.com/Andre601/HexChat/issues
#
# Additional information may be found on the wiki: https://wiki.powerplugins.net/wiki/hexchat
#
# |====================|
# |    Placeholders    |
# |====================|
#
# HexChat provises own placeholders that can be used for the different formats, but also for the "format" option of the
# "console" section below.
#
# Placeholders:
# - %msg%     ->  The message that was send.
# - %player%  ->  The player's name.
# - %world%   ->  The name of the world.
#
# |===============|
# |    Console    |
# |===============|
#
# Change settings of the console (if it should log messages, look of the message, etc.)
#
console:
  #
  # Should the colorful HexChat banner be displayed in the Console?
  #
  banner: true
  #
  # Should messages send by players be logged in the console?
  #
  log: true
  #
  # How should the message format look like? This is only used when the "log" option above is set to true.
  #
  format: '<%player%> %msg%'
#
# |===============|
# |    Formats    |
# |===============|
#
# This section allows you to set the formats that players may use.
#
formats:
  #
  # Each format name has to be a unique name that can be assigned through the permission hexchat.format.<format>
  # You need to keep one format called "default" that will be applied if the player doesn't have permission for any of
  # the other formats.
  #
  default:
    #
    # Each section needs to be a unique name similar to the format name.
    # How it is called is actually not important as long as it is a string.
    #
    worldStart:
      #
      # The text to display in chat.
      #
      # You can use placeholders from both this plugin and PlaceholderAPI.
      #
      text: '['
    worldBody:
      #
      # The text to display in chat.
      #
      # You can use placeholders from both this plugin and PlaceholderAPI.
      #
      text: '%world%'
      #
      # The primary color to display the above text in.
      # This can be overriden using any normal chat color code in the above text section. Leaving this away/empty
      # defaults to WHITE
      #
      # For all available chat color names, check this page:
      # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
      #
      # Thanks to 1.16 can you also use ANY hexadecimal color code available, by starting the String with a # followed
      # by a 6 character hex code (f.e. #FF0000 for red)
      #
      color: '#2980B9'
      #
      # Allows you to apply a hover text to this section.
      #
      hover:
      - '&7This Player is currently in'
      - '&7the world &b%world%'
    worldEnd:
      #
      # The text to display in chat.
      #
      # You can use placeholders from both this plugin and PlaceholderAPI.
      #
      text: '] '
    name:
      #
      # The text to display in chat.
      #
      # You can use placeholders from both this plugin and PlaceholderAPI.
      #
      text: '%player%'
      #
      # The primary color to display the above text in.
      # This can be overriden using any normal chat color code in the above text section. Leaving this away/empty
      # defaults to WHITE
      #
      # For all available chat color names, check this page:
      # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
      #
      # Thanks to 1.16 can you also use ANY hexadecimal color code available, by starting the String with a # followed
      # by a 6 character hex code (f.e. #FF0000 for red)
      #
      color: '#00FF00'
      #
      # Allows you to apply a hover text to this section.
      #
      hover:
      - '&7Click to send the player a message!'
      #
      # Allows you to apply a click action for this section.
      #
      click:
        #
        # What type of click action this would be.
        #
        # Available options:
        # - execute -> Executes a command as the player clicking on it.
        # - suggest -> Suggests a command to the player (puts it into the players chatbox)
        # - copy    -> Copies the provided text into the player's clipboard.
        #              This can only be used on 1.15+ and will default to 'suggest' when used on 1.14 or older.
        #
        type: 'suggest'
        value: '/msg %player% '
    separator:
      #
      # The text to display in chat.
      #
      # You can use placeholders from both this plugin and PlaceholderAPI.
      #
      text: ': '
    msg:
      #
      # The text to display in chat.
      #
      # You can use placeholders from both this plugin and PlaceholderAPI.
      #
      text: '%msg%'
      #
      # The primary color to display the above text in.
      # This can be overriden using any normal chat color code in the above text section. Leaving this away/empty
      # defaults to WHITE
      #
      # For all available chat color names, check this page:
      # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
      #
      # Thanks to 1.16 can you also use ANY hexadecimal color code available, by starting the String with a # followed
      # by a 6 character hex code (f.e. #FF0000 for red)
      #
      color: '#95A5A6'