name: HexChat
author: Andre_601
version: '1.2.0'

api-version: '1.16'

main: 'com.andre601.hexchat.HexChat'

softdepend:
- PlaceholderAPI

permissions: 
  hexchat.format.default:
    default: true
    description: 'The default permission for the chat format'
  hexchat.*:
    default: op
    description: 'Gives access to all HexChat permissions'
    children: 
      hexchat.admin: true
  hexchat.admin:
    default: op
    description: 'Gives access to all HexChat permissions'
    children: 
      hexchat.command.*: true
      hexchat.color: true
  hexchat.command.*:
    default: op
    description: 'Gives access to all HexChat Command permissions'
    children: 
      hexchat.command.help: true
      hexchat.command.reload: true
      hexchat.command.formats: true
  hexchat.command.help:
    default: op
    description: 'Gives access to /hexchat help [command]'
  hexchat.command.reload:
    default: op
    description: 'Gives access to /hexchat reload'
  hexchat.command.formats:
    default: op
    description: 'Gives access to /hexchat formats'
  hexchat.color:
    default: op
    description: 'Allows the usage of color and formatting codes in messages.'